version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure your Dockerfile is in the same directory
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=34.50.65.104
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=vehicle-counter
    depends_on:
      - mysql
    networks:
      - vehicle_counter_network

  mysql:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: vehicle-counter
    ports:
      - "3306:3306"
    networks:
      - vehicle_counter_network

networks:
  vehicle_counter_network:
    driver: bridge
